### ISSUE TITLE
Responds to every input

### ISSUE THREAD

**Issue by hackslayd0g** [kalebhermes/swdice-discord#16]
Possible to have bot only respond when given the proper commands? 
e.g. the bot only responding when you type /roll instead of responding to everything

**Comment by kalebhermes** [comment]
Hey! Sorry about that. That's what happens when you test everything, but don't use the latest push in a live game!

I've pushed a fix for the issue, and you should be good! Please let me know if it's not working properly!

**Comment by hackslayd0g** [comment]
Excellent! Works fantastic!
